"""adiciona configuracoes da empresa

Revision ID: 0055a231c0e9
Revises: ee541281c641
Create Date: 2026-07-11 14:08:46.037546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0055a231c0e9'
down_revision = 'ee541281c641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=180), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=120), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('exibir_logo_relatorios', sa.Boolean(), nullable=False),
    sa.Column('rodape_relatorios', sa.String(length=300), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_configuracoes_empresa_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracoes_empresa')),
    sa.UniqueConstraint('empresa_id', name='uq_configuracoes_empresa_empresa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes_empresa')
    # ### end Alembic commands ###
