"""adiciona modulo de abastecimentos

Revision ID: 0430779b342e
Revises: 81bb3a7fd7c6
Create Date: 2026-07-11 13:09:50.511603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0430779b342e'
down_revision = '81bb3a7fd7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('posto', sa.String(length=150), nullable=False),
    sa.Column('combustivel', sa.String(length=30), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_litro', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('tanque_cheio', sa.Boolean(), nullable=False),
    sa.Column('numero_nota', sa.String(length=80), nullable=True),
    sa.Column('comprovante', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_abastecimentos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('fk_abastecimentos_motorista_id_motoristas')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_abastecimentos_obra_id_obras')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_abastecimentos_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_abastecimentos_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abastecimentos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abastecimentos')
    # ### end Alembic commands ###
