"""adiciona modulo de obras

Revision ID: 3b60802e4c81
Revises: 01e30df23aa6
Create Date: 2026-07-11 12:01:02.974260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b60802e4c81'
down_revision = '01e30df23aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_obras_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obras')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_obra_empresa_codigo')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_empresas_cnpj'), ['cnpj'])

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_planos_nome'), ['nome'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_usuario'), ['usuario'])

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_veiculos_obra_id_obras'), 'obras', ['obra_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_veiculos_obra_id_obras'), type_='foreignkey')
        batch_op.drop_column('obra_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_usuario'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_usuarios_email'), type_='unique')

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_planos_nome'), type_='unique')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_empresas_cnpj'), type_='unique')

    op.drop_table('obras')
    # ### end Alembic commands ###
