"""adiciona modulo de motoristas

Revision ID: 67228cd462ee
Revises: 725f3e8056fb
Create Date: 2026-07-11 11:48:16.405762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67228cd462ee'
down_revision = '725f3e8056fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cnh', sa.String(length=11), nullable=False),
    sa.Column('categoria_cnh', sa.String(length=5), nullable=False),
    sa.Column('validade_cnh', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'cnh', name='uq_motorista_empresa_cnh'),
    sa.UniqueConstraint('empresa_id', 'cpf', name='uq_motorista_empresa_cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motoristas')
    # ### end Alembic commands ###
