"""adiciona diario de bordo

Revision ID: 81bb3a7fd7c6
Revises: 3b60802e4c81
Create Date: 2026-07-11 12:07:13.739452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bb3a7fd7c6'
down_revision = '3b60802e4c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarios_bordo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=False),
    sa.Column('hora_retorno', sa.Time(), nullable=True),
    sa.Column('km_inicial', sa.Integer(), nullable=False),
    sa.Column('km_final', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(length=200), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('finalidade', sa.String(length=250), nullable=True),
    sa.Column('ocorrencias', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_diarios_bordo_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('fk_diarios_bordo_motorista_id_motoristas')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_diarios_bordo_obra_id_obras')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_diarios_bordo_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diarios_bordo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diarios_bordo')
    # ### end Alembic commands ###
