"""adiciona modulo de manutencoes

Revision ID: ee541281c641
Revises: 0430779b342e
Create Date: 2026-07-11 13:20:21.357463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee541281c641'
down_revision = '0430779b342e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('fornecedor', sa.String(length=150), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('valor_pecas', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_mao_obra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('proxima_manutencao_data', sa.Date(), nullable=True),
    sa.Column('proxima_manutencao_km', sa.Integer(), nullable=True),
    sa.Column('numero_nota', sa.String(length=80), nullable=True),
    sa.Column('comprovante', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_manutencoes_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_manutencoes_obra_id_obras')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_manutencoes_usuario_id_usuarios')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_manutencoes_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manutencoes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manutencoes')
    # ### end Alembic commands ###
